name: docker-example

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unit test run
        uses: .github/actions/docker-unit-tests
#  release-build:
#    runs-on: ubuntu-latest
#    name: Build the release target
#    steps:
#      # To use this repository's private action,
#      # you must check out the repository
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Unit test run
#        uses: ./ # Uses an action in the root directory